name: CI-BlackDuck-Basic
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Black Duck Scan
        uses: synopsys-sig/synopsys-action@v1.11.0
        
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          
        with:
          blackduck_url: ${{ vars.BLACKDUCK_URL }}
          blackduck_token: ${{ secrets.BLACKDUCK_TOKEN }}
         
          blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'
          
          blackduck_fixpr_enabled: true
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required when Fix PRs is enabled
          
          blackduck_prcomment_enabled: true 

          ### SARIF report generation and upload to GitHub Adavanced Security: Uncomment below to enable
          blackduck_reports_sarif_create: true # Create Black Duck SARIF report and upload it as artifact
          blackduck_upload_sarif_report: true  # Upload Black Duck SARIF report in GitHub Advanced Security tab
